version: '2'
services:
    hermancards-app:
        image: hermancards
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://hermancards-postgresql:5432/hermancards
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    hermancards-postgresql:
        extends:
            file: postgresql.yml
            service: hermancards-postgresql
